### ISSUE TITLE
testnet insight-api does not allow CORS

### ISSUE THREAD

**Issue by qcoreprotocol** [qtumproject/insight-api#16]
When I use QtumWallet JS library to read contract infomation on testnet, I receive CORS error below

```
(index):1 Access to XMLHttpRequest at 'https://testnet.qtum.org/insight-api/contracts/adcbf0ac6a351e5f0b86eec5a4df288e62abacc0/info' from origin 'https://www.qcoreprotocol.org' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.
```
Same error occurs when I use localhost

```
from origin 'http://localhost:3000' has been blocked by CORS policy
```

if I open the testnet contract link in browser it works, however we need to use it with Qtumwallet-JS library so we have to find a workaround for CORS

A quick google search indicates this should be fixed at server API side: [stackoverflow post](https://stackoverflow.com/questions/22343384/the-access-control-allow-origin-header-contains-multiple-values)

For example if the web api is coded in .net, the server config should add below
```
config.EnableCors(new EnableCorsAttribute(Properties.Settings.Default.Cors, "", ""))
```
as well as
```

app.UseCors(CorsOptions.AllowAll);
```
We only need to get it working for testnet.qtum.org for now.
```
https://testnet.qtum.org/insight-api/contracts/adcbf0ac6a351e5f0b86eec5a4df288e62abacc0/info
```

thank you

**Comment by qcoreprotocol** [comment]
can you add cors headers to the response back for test.qtum.info server please

https://github.com/qtumproject/insight-api/blob/f369fd4b1d44a04eb90e7e04779ac211cd5c1c12/lib/index.js#L347

```
//Enable CORS
  // app.use(function(req, res, next) {

  //   res.header('Access-Control-Allow-Origin', '*');
  //   res.header('Access-Control-Allow-Methods', 'GET, HEAD, PUT, POST, OPTIONS');
  //   res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Content-Length, Cache-Control, cf-connecting-ip');

  //   var method = req.method && req.method.toUpperCase && req.method.toUpperCase();

  //   if (method === 'OPTIONS') {
  //     res.statusCode = 204;
  //     res.end();
  //   } else {
  //     next();
  //   }
  // });


```

**Comment by hayeah** [comment]
@qcoreprotocol this issue is now resolved. the cors was in fact already enabled:

https://github.com/qtumproject/insight-api/blob/f369fd4b1d44a04eb90e7e04779ac211cd5c1c12/lib/index.js#L345

There was a misconfiguration with downstream revere proxy, which the op team had now fixed.

CORS curl test:

```
curl -H "Origin: https://foobar.example.com/" \
  -H "Access-Control-Request-Method: POST" \
  -H "Access-Control-Request-Headers: X-Requested-With" \
  -X OPTIONS -i \
  https://explorer.qtum.org/insight-api/tx/send
```

returns 

```
HTTP/1.1 204 No Content
Date: Tue, 10 Nov 2020 03:09:07 GMT
Content-Length: 0
Connection: keep-alive
Set-Cookie: __cfduid=d7fd09eea77e5c6b8581232ad590cbb4b1604977747; expires=Thu, 10-Dec-20 03:09:07 GMT; path=/; domain=.qtum.org; HttpOnly; SameSite=Lax
x-powered-by: Express
x-ratelimit-limit: 170
x-ratelimit-remaining: 166
access-control-allow-origin: *
access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
vary: Access-Control-Request-Headers
access-control-allow-headers: X-Requested-With
CF-Cache-Status: DYNAMIC
cf-request-id: 0651b9ff4d0000a24389217000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=X4HPC%2F7y3D1VU5X5tePX%2FYVNuHVZxYkg7uqFAf3z4ls6cuBGESoou7BZEJLz6JkeZcB2bEBRSFq8S2SKtMZ1lJ%2BrCGfgp43A02Z06TDMNaLnPA%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 5efc92ababfda243-ICN

```

**Comment by qcoreprotocol** [comment]
Hi Howard, thank you, can you make the changes to **test.qtum.info** as well

we are still getting error

```
Access to XMLHttpRequest at 'https://testnet.qtum.org/insight-api/contracts/adcbf0ac6a351e5f0b86eec5a4df288e62abacc0/info' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

```

**Comment by hayeah** [comment]
@qcoreprotocol hi, i think you are using the wrong testnet insight API domain. try `https://testnet.qtum.org`

```
curl -H "Origin: https://foobar.example.com/" \
  -H "Access-Control-Request-Method: POST" \
  -H "Access-Control-Request-Headers: X-Requested-With" \
  -X OPTIONS -i \
  https://testnet.qtum.org/insight-api/tx/send
```

**Comment by qcoreprotocol** [comment]
sorry it is **testnet.qtum.org** that throws the error. 
```Access to XMLHttpRequest at 'https://testnet.qtum.org/insight-api/contracts/adcbf0ac6a351e5f0b86eec5a4df288e62abacc0/info' ```

```
Access to XMLHttpRequest at 'https://testnet.qtum.org/insight-api/contracts/adcbf0ac6a351e5f0b86eec5a4df288e62abacc0/info' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

```

if I click that link it works, but it get blocked when I call it via Axios library on the web

**Comment by qcoreprotocol** [comment]
Also I think CORS was blocked by the browser (Chrome) so cURL always returns data. However if using Axios library to access `https://testnet.qtum.org` it throws CORS error

**Comment by qcoreprotocol** [comment]
cURL works but it is still displaying CORS error for testnet.qtum.org if access via browser
@hayeah

**Comment by qcoreprotocol** [comment]
Looks like it is resolved on testnet thanks @hayeah
